apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qgnet-crd-rolebinding
subjects:
  - kind: ServiceAccount
    name: qgnet
    namespace: qgnet
roleRef:
  kind: ClusterRole
  name: custom-resource-definitions
  apiGroup: rbac.authorization.k8s.io
