# This is a template for adding the Role and RoleBinding, ClusterRole and ClusterRoleBinding needed
# by the qgnet project, in order to grant the additional permissions needed by the community-based
# Argo Workflow helm chart.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qgnet-argo-clusterlevel
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "update", "get", "list", "watch", "delete", "patch", "deletecollection" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles", "clusterrolebindings" ]
    verbs: [ "create", "update", "get", "list", "watch", "delete", "patch", "deletecollection", "bind", "escalate" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qgnet-argo-clusterlevel
subjects:
  - kind: ServiceAccount
    name: qgnet
    namespace: qgnet
roleRef:
  kind: ClusterRole
  name: qgnet-argo-clusterlevel
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qgnet-argo
  namespace: qgnet
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings" ]
    verbs: [ "create", "update", "get", "list", "watch", "delete" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "list" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    resourceNames: [ "workflow-controller", "workflow-controller-lease" ]
    verbs: [ "get", "watch", "update", "patch", "delete" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qgnet-argo
  namespace: qgnet
subjects:
  - kind: ServiceAccount
    name: qgnet
    namespace: qgnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qgnet-argo
