# This is a template for adding the Role and RoleBinding needed by the qgnet project, in order to
# grant the additional permissions needed by the community-based Argo Workflow.
# The RoleBinding should be bound to the same ServiceAccount used by Argo Workflows.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qgnet-argo
  namespace: qgnet
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowartifactgctasks"]
  verbs: ["list" "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowartifactgctasks/status"]
  verbs: ["patch"]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qgnet-argo
  namespace: qgnet
subjects:
  - kind: ServiceAccount
    name: qgnet
    namespace: qgnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qgnet-argo
