apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: docker.io/busybox:1.29
        args: [sh, -c, 'sleep 9999999999']
        volumeMounts:
          - name: cephfs-gnis-pv
            mountPath: /var/lib/www/html
          - name: cephfs-temp-cache-volume
            mountPath: /tmp/temp-cache
      volumes:
        - name: cephfs-gnis-pv
          persistentVolumeClaim:
            claimName: cephfs-gnis-pvc
            readOnly: false
        - name: cephfs-temp-cache-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: csi-cephfs-sc-ephemeral
                resources:
                  requests:
                    storage: 1Gi
