kind: PersistentVolume
apiVersion: v1
metadata:
  name: virtuoso-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data"
