####################################################################################################
## NEVER COMMIT SECRETS TO PUBLIC GIT REPOSITORIES!
## After generating a token, add it to a new kubeconfig file and push a GPG ENCRYPTED copy to our
## private security repo
####################################################################################################
##
## This template creates a Secret in the 'shared' namespace, which can be used to authenticate as
## the shared ServiceAccount named ${SERVICE_ACCOUNT}, in order to access the cluster with limited
## permissions (e.g. for reading logs etc.)
## A kubeconfig file containing the base64-decoded version of the ${BASE64_SECRET} should then be
## kept GPG ENCRYPTED in the private security repo, and provided to users approved for such access.
##
## Prerequisite:
## - A ServiceAccount named: ${SERVICE_ACCOUNT} in the 'shared' namespace (e.g. 'log-reader-shared')
##
## To use this template, replace:
## - ${SERVICE_ACCOUNT} with the name of the shared ServiceAccount (e.g. 'log-reader-shared')
## - ${BASE64_SECRET} with the base64-encoded version of a newly-generated secure token.
##   - Example token generation and encoding:
##     $  export BASE64_SECRET=$(head -c 25 /dev/random | shasum -a 256 | head -c 25 | base64)
##
## Output:
## - A Secret named: "${SERVICE_ACCOUNT}-secret" in the 'shared' namespace
##
apiVersion: v1
kind: Secret
metadata:
  name: "${SERVICE_ACCOUNT}-secret"
  namespace: shared
  annotations:
    kubernetes.io/service-account.name: "$SERVICE_ACCOUNT"
type: kubernetes.io/service-account-token
data:
  extra: "$BASE64_SECRET"
