## This template creates a ServiceAccount in the 'shared' namespace, that may be bound to
## ClusterRoles providing access to resources in one or more target namespaces.
## To use this template, replace ${SERVICE_ACCOUNT} with the desired name of the shared SA. For
## clarity, make the SA name short and descriptive of its function, and append "-shared" to the end
## (e.g. 'log-reader-shared').
## Output:
## - A ServiceAccount named: "${SERVICE_ACCOUNT}" in the 'shared' namespace
##
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "$SERVICE_ACCOUNT"
  namespace: shared
