apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-gnis-pvc
  namespace: gnis
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: cephfs-gnis-pv
