---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  # Required for statically provisioned volumes
  userID: k8sdevsubvoluser
  userKey: <Ceph auth key corresponding to ID above from /etc/ceph>

  # These are not currently used by DataONE k8s
  # Required for dynamically provisioned volumes
  #adminID: <plaintext ID>
  #adminKey: <Ceph auth key corresponding to ID above>
